### ISSUE TITLE
ERROR in app: Exception on /dashboard

### ISSUE THREAD

**Issue by RaithSphere** [glitchfur/NeosVR-Headless-WebUI#1]
neosvr-headless-webui    | [2022-07-17 14:05:31 +0000] [9] [INFO] Booting worker with pid: 9
neosvr-headless-webui    | [2022-07-17 14:05:31 +0000] [10] [INFO] Booting worker with pid: 10
neosvr-headless-webui    | [2022-07-17 14:05:31 +0000] [11] [INFO] Booting worker with pid: 11
neosvr-headless-webui    | [2022-07-17 14:06:01,014] ERROR in app: Exception on /dashboard [GET]
neosvr-headless-webui    | Traceback (most recent call last):
neosvr-headless-webui    |   File "/home/webui/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
neosvr-headless-webui    |     response = self.full_dispatch_request()
neosvr-headless-webui    |   File "/home/webui/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
neosvr-headless-webui    |     rv = self.handle_user_exception(e)
neosvr-headless-webui    |   File "/home/webui/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
neosvr-headless-webui    |     rv = self.dispatch_request()
neosvr-headless-webui    |   File "/home/webui/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
neosvr-headless-webui    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
neosvr-headless-webui    |   File "/home/webui/neosvr_headless_webui/auth.py", line 45, in wrapped_view
neosvr-headless-webui    |     return view(*args, **kwargs)
neosvr-headless-webui    |   File "/home/webui/neosvr_headless_webui/dashboard.py", line 40, in dashboard
neosvr-headless-webui    |     conn = connect_manager()
neosvr-headless-webui    |   File "/home/webui/neosvr_headless_webui/dashboard.py", line 30, in connect_manager
neosvr-headless-webui    |     return connect(
neosvr-headless-webui    |   File "/home/webui/.local/lib/python3.10/site-packages/rpyc/utils/factory.py", line 102, in connect
neosvr-headless-webui    |     s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
neosvr-headless-webui    |   File "/home/webui/.local/lib/python3.10/site-packages/rpyc/core/stream.py", line 173, in connect
neosvr-headless-webui    |     return cls(cls._connect(host, port, **kwargs))
neosvr-headless-webui    |   File "/home/webui/.local/lib/python3.10/site-packages/rpyc/core/stream.py", line 125, in _connect
neosvr-headless-webui    |     s = socket_backoff_connect(family, socktype, proto, sockaddr, timeout, attempts)
neosvr-headless-webui    |   File "/home/webui/.local/lib/python3.10/site-packages/rpyc/lib/__init__.py", line 131, in socket_backoff_connect
neosvr-headless-webui    |     sock.connect(addr)
neosvr-headless-webui    | ConnectionRefusedError: [Errno 111] Connection refused

**Comment by RaithSphere** [comment]
Never mind didn't read something correct
